apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: registration-app-prod
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: 'https://github.com/qiot-project/qiot-ubi-all-registration-gitops'
    path: prod
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: manufacturing-prod   
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
